apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    type: web
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: type
                operator: In
                values:
                  - redis
          topologyKey: "kubernetes.io/hostname"
  containers:
  - name: web
    image: supergiantkir/animals:bear
