apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    type: web-pod
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: type
            operator: In
            values:
            - redis-pod
        topologyKey: kubernetes.io/hostname
  containers:
  - name: web-pod
    image: supergiantkir/animals:bear
