apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    type: redis-pod
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: type
            operator: In
            values:
            - mysql-pod
        topologyKey: kubernetes.io/hostname
  containers:
  - name: redis-pod
    image: supergiantkir/animals:bear
