apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  dbname: {{ .Values.dbname }}
  dbtable: {{ .Values.dbtable }}
  image: {{ .Values.image }}:{{ .Values.tag  }}
  
  eat: {{ .Values.food.eat | upper | trunc 13 | quote }}
  drink: {{ .Values.food.drink | upper}}
