apiVersion: v1 # K8S API Version
kind: Pod  # Object Type
metadata: 
 name: shysh-container 
spec:
 containers: 
 - name: springapp-shysh 
   image: yanivomc/spring-music:latest 
   ports: 
   - containerPort: 8081
 - name: springapp
   image: yanivomc/spring-music:latest
   ports: 
   - containerPort: 8080
